project_id = "exam-transfer"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
major_version = 17

[auth]
enabled = true
enable_signup = false
site_url = "http://localhost:5048"
additional_redirect_urls = ["http://localhost:5048"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
